(defun let-example (x)
(format t "Parameter: ~a~%" x)
(let ((x 2))
    (format t "Outer LET: ~a~%" x)
    (let ((x 3))
        (format t "Inner LET: ~a~%" x))
    (format t "Outer LET: ~a~%" x))
(format t "Parameter: ~a~%" x))

(closure-example 5)
